// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:599

#ifndef _TAO_IDL_IBASICEVENTCORBAS_T_OOI24L_H_
#define _TAO_IDL_IBASICEVENTCORBAS_T_OOI24L_H_

#include /**/ "ace/pre.h"

// TAO_IDL - Generated from
// be\be_visitor_root\root_sth.cpp:68

namespace POA_IBASICEVENTCORBA_module
{
} // module IBASICEVENTCORBA_module

// TAO_IDL - Generated from
// be\be_codegen.cpp:1847


#if defined (ACE_TEMPLATES_REQUIRE_SOURCE)
#include "IBasicEventCorbaS_T.cpp"
#endif /* defined REQUIRED SOURCE */

#if defined (ACE_TEMPLATES_REQUIRE_PRAGMA)
#pragma implementation ("IBasicEventCorbaS_T.cpp")
#endif /* defined REQUIRED PRAGMA */

#include /**/ "ace/post.h"
#endif /* ifndef */

