// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:152

#ifndef _TAO_IDL_IBASICEVENTCORBAC_OOI24L_H_
#define _TAO_IDL_IBASICEVENTCORBAC_OOI24L_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "IBASICEVENTCORBA_Export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 1
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO IBASICEVENTCORBA_Export

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:38

namespace IBASICEVENTCORBA_module
{

  // TAO_IDL - Generated from
  // be\be_visitor_enum\enum_ch.cpp:47

  enum VariantTypes
  {
    VT_LONG,
    VT_ULONG,
    VT_DOUBLE,
    VT_LONGLONG,
    VT_ULONGLONG,
    VT_STRING
  };

  typedef VariantTypes &VariantTypes_out;

  // TAO_IDL - Generated from
  // be\be_type.cpp:261

  class Arg;

  typedef
    ::TAO_Var_Var_T<
        Arg
      >
    Arg_var;

  typedef
    ::TAO_Out_T<
        Arg
      >
    Arg_out;

  class IBASICEVENTCORBA_Export Arg
  {
  public:
    Arg (void);
    Arg (const Arg &);
    ~Arg (void);

    Arg &operator= (const Arg &);

    // TAO_IDL - Generated from
    // be\be_visitor_union\discriminant_ch.cpp:70

    void _d (IBASICEVENTCORBA_module::VariantTypes);
    IBASICEVENTCORBA_module::VariantTypes _d (void) const;

    // TAO_IDL - Generated from
    // be\be_type.cpp:307

    
    typedef Arg_var _var_type;
    typedef Arg_out _out_type;

    // TAO_IDL - Generated from
    // be\be_visitor_union_branch\public_ch.cpp:452

    void lValue ( ::CORBA::Long);
    ::CORBA::Long lValue (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_union_branch\public_ch.cpp:452

    void ulValue ( ::CORBA::ULong);
    ::CORBA::ULong ulValue (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_union_branch\public_ch.cpp:452

    void dValue ( ::CORBA::Double);
    ::CORBA::Double dValue (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_union_branch\public_ch.cpp:452

    void llValue ( ::CORBA::ULongLong);
    ::CORBA::ULongLong llValue (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_union_branch\public_ch.cpp:452

    void ullValue ( ::CORBA::ULongLong);
    ::CORBA::ULongLong ullValue (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_union_branch\public_ch.cpp:583

    void strValue (char *);
    void strValue (const char *);
    void strValue (const ::CORBA::String_var&);
    const char *strValue (void) const;

    // TAO_IDL - Generated from
    // be\be_visitor_union\union_ch.cpp:124

    void _default (void);
  private:
    IBASICEVENTCORBA_module::VariantTypes disc_;

    union
    {
      // TAO_IDL - Generated from
      // be\be_visitor_union_branch\private_ch.cpp:380
      ::CORBA::Long lValue_;
      // TAO_IDL - Generated from
      // be\be_visitor_union_branch\private_ch.cpp:380
      ::CORBA::ULong ulValue_;
      // TAO_IDL - Generated from
      // be\be_visitor_union_branch\private_ch.cpp:380
      ::CORBA::Double dValue_;
      // TAO_IDL - Generated from
      // be\be_visitor_union_branch\private_ch.cpp:380
      ::CORBA::ULongLong llValue_;
      // TAO_IDL - Generated from
      // be\be_visitor_union_branch\private_ch.cpp:380
      ::CORBA::ULongLong ullValue_;
      // TAO_IDL - Generated from
      // be\be_visitor_union_branch\private_ch.cpp:477
      char *strValue_;
    } u_;

    /// TAO extension - frees any allocated storage.
    void _reset (void);
  };

  // TAO_IDL - Generated from
  // be\be_type.cpp:261

  struct EventArg;

  typedef
    ::TAO_Var_Var_T<
        EventArg
      >
    EventArg_var;

  typedef
    ::TAO_Out_T<
        EventArg
      >
    EventArg_out;

  // TAO_IDL - Generated from
  // be\be_visitor_structure\structure_ch.cpp:51

  struct IBASICEVENTCORBA_Export EventArg
  {

    // TAO_IDL - Generated from
    // be\be_type.cpp:307

    
    typedef EventArg_var _var_type;
    typedef EventArg_out _out_type;
    
    ::TAO::String_Manager id_;
    

    IBASICEVENTCORBA_module::Arg arg_;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_sequence\sequence_ch.cpp:102

#if !defined (_IBASICEVENTCORBA_MODULE_EVENTARGSEQ_CH_)
#define _IBASICEVENTCORBA_MODULE_EVENTARGSEQ_CH_

  class EventArgSeq;

  typedef
    ::TAO_VarSeq_Var_T<
        EventArgSeq
      >
    EventArgSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        EventArgSeq
      >
    EventArgSeq_out;

  class IBASICEVENTCORBA_Export EventArgSeq
    : public
        ::TAO::unbounded_value_sequence<
            EventArg
          >
  {
  public:
    EventArgSeq (void);
    EventArgSeq ( ::CORBA::ULong max);
    EventArgSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      EventArg* buffer,
      ::CORBA::Boolean release = false);
    EventArgSeq (const EventArgSeq &);
    virtual ~EventArgSeq (void);
    

    // TAO_IDL - Generated from
    // be\be_type.cpp:307

    
    typedef EventArgSeq_var _var_type;
    typedef EventArgSeq_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_type.cpp:261

  struct EventSpec;

  typedef
    ::TAO_Var_Var_T<
        EventSpec
      >
    EventSpec_var;

  typedef
    ::TAO_Out_T<
        EventSpec
      >
    EventSpec_out;

  // TAO_IDL - Generated from
  // be\be_visitor_structure\structure_ch.cpp:51

  struct IBASICEVENTCORBA_Export EventSpec
  {

    // TAO_IDL - Generated from
    // be\be_type.cpp:307

    
    typedef EventSpec_var _var_type;
    typedef EventSpec_out _out_type;
    
    ::CORBA::Long param_number;
    ::TAO::String_Manager spec_string;
  };

  // TAO_IDL - Generated from
  // be\be_visitor_sequence\sequence_ch.cpp:102

#if !defined (_IBASICEVENTCORBA_MODULE_EVENTSPECSEQ_CH_)
#define _IBASICEVENTCORBA_MODULE_EVENTSPECSEQ_CH_

  class EventSpecSeq;

  typedef
    ::TAO_VarSeq_Var_T<
        EventSpecSeq
      >
    EventSpecSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        EventSpecSeq
      >
    EventSpecSeq_out;

  class IBASICEVENTCORBA_Export EventSpecSeq
    : public
        ::TAO::unbounded_value_sequence<
            EventSpec
          >
  {
  public:
    EventSpecSeq (void);
    EventSpecSeq ( ::CORBA::ULong max);
    EventSpecSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      EventSpec* buffer,
      ::CORBA::Boolean release = false);
    EventSpecSeq (const EventSpecSeq &);
    virtual ~EventSpecSeq (void);
    

    // TAO_IDL - Generated from
    // be\be_type.cpp:307

    
    typedef EventSpecSeq_var _var_type;
    typedef EventSpecSeq_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be\be_type.cpp:261

  struct BasicEventCorba;

  typedef
    ::TAO_Var_Var_T<
        BasicEventCorba
      >
    BasicEventCorba_var;

  typedef
    ::TAO_Out_T<
        BasicEventCorba
      >
    BasicEventCorba_out;

  // TAO_IDL - Generated from
  // be\be_visitor_structure\structure_ch.cpp:51

  struct IBASICEVENTCORBA_Export BasicEventCorba
  {

    // TAO_IDL - Generated from
    // be\be_type.cpp:307

    
    typedef BasicEventCorba_var _var_type;
    typedef BasicEventCorba_out _out_type;
    
    ::TAO::String_Manager namespace_;
    ::CORBA::Long event_id_;
    ::TAO::String_Manager format_;
    IBASICEVENTCORBA_module::EventSpecSeq map_spec_;
    IBASICEVENTCORBA_module::EventArgSeq args_;
    ::TAO::String_Manager node_id_;
    ::TAO::String_Manager source_id_;
    ::CORBA::Long severity_;
  };

// TAO_IDL - Generated from
// be\be_visitor_module\module_ch.cpp:67

} // module IBASICEVENTCORBA_module

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::VariantTypes>
    : public
        Basic_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::VariantTypes,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:1058

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::Arg>
    : public
        Var_Size_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::Arg,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::EventArg>
    : public
        Var_Size_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::EventArg,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::EventArgSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::EventArgSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::EventSpec>
    : public
        Var_Size_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::EventSpec,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::EventSpecSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::EventSpecSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::IBASICEVENTCORBA_module::BasicEventCorba>
    : public
        Var_Size_Arg_Traits_T<
            ::IBASICEVENTCORBA_module::BasicEventCorba,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_enum\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, IBASICEVENTCORBA_module::VariantTypes _tao_enumerator);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, IBASICEVENTCORBA_module::VariantTypes &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_union\cdr_op_ch.cpp:41


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const IBASICEVENTCORBA_module::Arg &);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, IBASICEVENTCORBA_module::Arg &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_structure\cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const IBASICEVENTCORBA_module::EventArg &);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, IBASICEVENTCORBA_module::EventArg &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_sequence\cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_IBASICEVENTCORBA_module_EventArgSeq_H_
#define _TAO_CDR_OP_IBASICEVENTCORBA_module_EventArgSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const IBASICEVENTCORBA_module::EventArgSeq &_tao_sequence);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    IBASICEVENTCORBA_module::EventArgSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_IBASICEVENTCORBA_module_EventArgSeq_H_ */

// TAO_IDL - Generated from
// be\be_visitor_structure\cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const IBASICEVENTCORBA_module::EventSpec &);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, IBASICEVENTCORBA_module::EventSpec &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_sequence\cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_IBASICEVENTCORBA_module_EventSpecSeq_H_
#define _TAO_CDR_OP_IBASICEVENTCORBA_module_EventSpecSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const IBASICEVENTCORBA_module::EventSpecSeq &_tao_sequence);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    IBASICEVENTCORBA_module::EventSpecSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_IBASICEVENTCORBA_module_EventSpecSeq_H_ */

// TAO_IDL - Generated from
// be\be_visitor_structure\cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

IBASICEVENTCORBA_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const IBASICEVENTCORBA_module::BasicEventCorba &);
IBASICEVENTCORBA_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, IBASICEVENTCORBA_module::BasicEventCorba &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "IBasicEventCorbaC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

