
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl BASICEVENTTRANSRESIMPL
// ------------------------------
#ifndef BASICEVENTTRANSRESIMPL_EXPORT_H
#define BASICEVENTTRANSRESIMPL_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (BASICEVENTTRANSRESIMPL_HAS_DLL)
#  define BASICEVENTTRANSRESIMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && BASICEVENTTRANSRESIMPL_HAS_DLL */

#if !defined (BASICEVENTTRANSRESIMPL_HAS_DLL)
#  define BASICEVENTTRANSRESIMPL_HAS_DLL 1
#endif /* ! BASICEVENTTRANSRESIMPL_HAS_DLL */

#if defined (BASICEVENTTRANSRESIMPL_HAS_DLL) && (BASICEVENTTRANSRESIMPL_HAS_DLL == 1)
#  if defined (BASICEVENTTRANSRESIMPL_BUILD_DLL)
#    define BASICEVENTTRANSRESIMPL_Export ACE_Proper_Export_Flag
#    define BASICEVENTTRANSRESIMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTTRANSRESIMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* BASICEVENTTRANSRESIMPL_BUILD_DLL */
#    define BASICEVENTTRANSRESIMPL_Export ACE_Proper_Import_Flag
#    define BASICEVENTTRANSRESIMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTTRANSRESIMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* BASICEVENTTRANSRESIMPL_BUILD_DLL */
#else /* BASICEVENTTRANSRESIMPL_HAS_DLL == 1 */
#  define BASICEVENTTRANSRESIMPL_Export
#  define BASICEVENTTRANSRESIMPL_SINGLETON_DECLARATION(T)
#  define BASICEVENTTRANSRESIMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* BASICEVENTTRANSRESIMPL_HAS_DLL == 1 */

// Set BASICEVENTTRANSRESIMPL_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (BASICEVENTTRANSRESIMPL_NTRACE)
#  if (ACE_NTRACE == 1)
#    define BASICEVENTTRANSRESIMPL_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define BASICEVENTTRANSRESIMPL_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !BASICEVENTTRANSRESIMPL_NTRACE */

#if (BASICEVENTTRANSRESIMPL_NTRACE == 1)
#  define BASICEVENTTRANSRESIMPL_TRACE(X)
#else /* (BASICEVENTTRANSRESIMPL_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define BASICEVENTTRANSRESIMPL_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (BASICEVENTTRANSRESIMPL_NTRACE == 1) */

#endif /* BASICEVENTTRANSRESIMPL_EXPORT_H */

// End of auto generated file.
