
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl BASICEVENTTRANSRES
// ------------------------------
#ifndef BASICEVENTTRANSRES_EXPORT_H
#define BASICEVENTTRANSRES_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (BASICEVENTTRANSRES_HAS_DLL)
#  define BASICEVENTTRANSRES_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && BASICEVENTTRANSRES_HAS_DLL */

#if !defined (BASICEVENTTRANSRES_HAS_DLL)
#  define BASICEVENTTRANSRES_HAS_DLL 1
#endif /* ! BASICEVENTTRANSRES_HAS_DLL */

#if defined (BASICEVENTTRANSRES_HAS_DLL) && (BASICEVENTTRANSRES_HAS_DLL == 1)
#  if defined (BASICEVENTTRANSRES_BUILD_DLL)
#    define BASICEVENTTRANSRES_Export ACE_Proper_Export_Flag
#    define BASICEVENTTRANSRES_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTTRANSRES_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* BASICEVENTTRANSRES_BUILD_DLL */
#    define BASICEVENTTRANSRES_Export ACE_Proper_Import_Flag
#    define BASICEVENTTRANSRES_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTTRANSRES_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* BASICEVENTTRANSRES_BUILD_DLL */
#else /* BASICEVENTTRANSRES_HAS_DLL == 1 */
#  define BASICEVENTTRANSRES_Export
#  define BASICEVENTTRANSRES_SINGLETON_DECLARATION(T)
#  define BASICEVENTTRANSRES_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* BASICEVENTTRANSRES_HAS_DLL == 1 */

// Set BASICEVENTTRANSRES_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (BASICEVENTTRANSRES_NTRACE)
#  if (ACE_NTRACE == 1)
#    define BASICEVENTTRANSRES_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define BASICEVENTTRANSRES_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !BASICEVENTTRANSRES_NTRACE */

#if (BASICEVENTTRANSRES_NTRACE == 1)
#  define BASICEVENTTRANSRES_TRACE(X)
#else /* (BASICEVENTTRANSRES_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define BASICEVENTTRANSRES_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (BASICEVENTTRANSRES_NTRACE == 1) */

#endif /* BASICEVENTTRANSRES_EXPORT_H */

// End of auto generated file.
