
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl BASICEVENTHANDLING
// ------------------------------
#ifndef BASICEVENTHANDLING_EXPORT_H
#define BASICEVENTHANDLING_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (BASICEVENTHANDLING_HAS_DLL)
#  define BASICEVENTHANDLING_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && BASICEVENTHANDLING_HAS_DLL */

#if !defined (BASICEVENTHANDLING_HAS_DLL)
#  define BASICEVENTHANDLING_HAS_DLL 1
#endif /* ! BASICEVENTHANDLING_HAS_DLL */

#if defined (BASICEVENTHANDLING_HAS_DLL) && (BASICEVENTHANDLING_HAS_DLL == 1)
#  if defined (BASICEVENTHANDLING_BUILD_DLL)
#    define BASICEVENTHANDLING_Export ACE_Proper_Export_Flag
#    define BASICEVENTHANDLING_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTHANDLING_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* BASICEVENTHANDLING_BUILD_DLL */
#    define BASICEVENTHANDLING_Export ACE_Proper_Import_Flag
#    define BASICEVENTHANDLING_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTHANDLING_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* BASICEVENTHANDLING_BUILD_DLL */
#else /* BASICEVENTHANDLING_HAS_DLL == 1 */
#  define BASICEVENTHANDLING_Export
#  define BASICEVENTHANDLING_SINGLETON_DECLARATION(T)
#  define BASICEVENTHANDLING_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* BASICEVENTHANDLING_HAS_DLL == 1 */

// Set BASICEVENTHANDLING_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (BASICEVENTHANDLING_NTRACE)
#  if (ACE_NTRACE == 1)
#    define BASICEVENTHANDLING_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define BASICEVENTHANDLING_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !BASICEVENTHANDLING_NTRACE */

#if (BASICEVENTHANDLING_NTRACE == 1)
#  define BASICEVENTHANDLING_TRACE(X)
#else /* (BASICEVENTHANDLING_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define BASICEVENTHANDLING_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (BASICEVENTHANDLING_NTRACE == 1) */

#endif /* BASICEVENTHANDLING_EXPORT_H */

// End of auto generated file.
