#ifndef __CLASSWITHRES_EVC_H__
#define __CLASSWITHRES_EVC_H__

#include "BasicEventHandling/BasicEventHandling.h"

BEGIN_EVENT_DECL_NAMESPACE(ClassWithResEvents)
	STATIC_EVENT_DECL(ev1)
	STATIC_EVENT_DECL(ev2)
	STATIC_EVENT_DECL(ev3)
END_EVENT_NAMESPACE()


#endif // __CLASSWITHRES_EVC_H__
