
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl BASICEVENTCORBA
// ------------------------------
#ifndef BASICEVENTCORBA_EXPORT_H
#define BASICEVENTCORBA_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (BASICEVENTCORBA_HAS_DLL)
#  define BASICEVENTCORBA_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && BASICEVENTCORBA_HAS_DLL */

#if !defined (BASICEVENTCORBA_HAS_DLL)
#  define BASICEVENTCORBA_HAS_DLL 1
#endif /* ! BASICEVENTCORBA_HAS_DLL */

#if defined (BASICEVENTCORBA_HAS_DLL) && (BASICEVENTCORBA_HAS_DLL == 1)
#  if defined (BASICEVENTCORBA_BUILD_DLL)
#    define BASICEVENTCORBA_Export ACE_Proper_Export_Flag
#    define BASICEVENTCORBA_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTCORBA_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* BASICEVENTCORBA_BUILD_DLL */
#    define BASICEVENTCORBA_Export ACE_Proper_Import_Flag
#    define BASICEVENTCORBA_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define BASICEVENTCORBA_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* BASICEVENTCORBA_BUILD_DLL */
#else /* BASICEVENTCORBA_HAS_DLL == 1 */
#  define BASICEVENTCORBA_Export
#  define BASICEVENTCORBA_SINGLETON_DECLARATION(T)
#  define BASICEVENTCORBA_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* BASICEVENTCORBA_HAS_DLL == 1 */

// Set BASICEVENTCORBA_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (BASICEVENTCORBA_NTRACE)
#  if (ACE_NTRACE == 1)
#    define BASICEVENTCORBA_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define BASICEVENTCORBA_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !BASICEVENTCORBA_NTRACE */

#if (BASICEVENTCORBA_NTRACE == 1)
#  define BASICEVENTCORBA_TRACE(X)
#else /* (BASICEVENTCORBA_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define BASICEVENTCORBA_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (BASICEVENTCORBA_NTRACE == 1) */

#endif /* BASICEVENTCORBA_EXPORT_H */

// End of auto generated file.
