#include "BasicEventTransResImpl/BasicEventTransResImpl.h"

BEGIN_EVENT_ENTRY()
	EVENT_ENTRY(AnyClassEvents, 1, "Bonjour, %1(%s) %2(%d)!")
	EVENT_ENTRY(AnyClassEvents, 2, "Quel age avez-vous?")
	EVENT_ENTRY(AnyClassEvents, 3, "J'ai %1(%d) ans.")
	EVENT_ENTRY(AnyClassEvents, 4, "Et vous?.")
	EVENT_ENTRY(BasicEventSyntaxCheckerEvents, 1, "Can not create output file: '%1(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 1, "Namespace '%1(%s)', Event '%2(%d)' already exists.")
	EVENT_ENTRY(BasicEventTransResEvents, 2, "Language '%1(%s)' already exists.")
	EVENT_ENTRY(BasicEventTransResEvents, 3, "Open file '%1(%s)' failed.")
	EVENT_ENTRY(BasicEventTransResEvents, 4, "BEGIN_EVENT_DEF_NAMESPACE macro not found (bad syntax in file '%1(%s)').")
	EVENT_ENTRY(BasicEventTransResEvents, 5, "END_EVENT_NAMESPACE macro not found (bad syntax in file '%1(%s)').")
	EVENT_ENTRY(BasicEventTransResEvents, 6, "STATIC_EVENT_DEF not found: bad syntax in file '%1(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 7, "'%1(%s)' - No comma in parameters.")
	EVENT_ENTRY(BasicEventTransResEvents, 8, "'%1(%s)' - Comma is missing in parameters.")
	EVENT_ENTRY(BasicEventTransResEvents, 9, "'%1(%s)' - Parsing parameters failed for id.")
	EVENT_ENTRY(BasicEventTransResEvents, 10, "Can not open the file with ACE_Configuration_Heap (file = %1(%s)).")
	EVENT_ENTRY(BasicEventTransResEvents, 11, "Can not import config from file '%1(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 12, "Can not open section '%1(%s)' in file '%2(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 13, "Can not get string value for section '%1(%s)' in file '%2(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 14, "No language specified.")
	EVENT_ENTRY(BasicEventTransResEvents, 15, "Namespace (%1(%s)) - ID (%2(%d)): not found in translation file. Format is set to the original one: '%3(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 16, "Invalid format '%1(%s)' in file '%2(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 17, "BEGIN_EVENT_DEF_NAMESPACE and END_EVENT_NAMESPACE mismatch in file '%1(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 18, "Error while adding event from file '%1(%s)'.")
	EVENT_ENTRY(BasicEventTransResEvents, 19, "Parsing error in file '%1(%s)'.")
	EVENT_ENTRY(CInproc1Events, 2, "HoHo")
	EVENT_ENTRY(CInproc1Events, 3, "Constructor")
	EVENT_ENTRY(Class2WithResEvents, 1, "Hello, %1(%s)!")
	EVENT_ENTRY(Class2WithResEvents, 2, "How old are you?")
	EVENT_ENTRY(Class2WithResEvents, 3, "I'm %1(%d) years old.")
	EVENT_ENTRY(Class2WithResEvents, 4, "And you?.")
	EVENT_ENTRY(ClassWithResEvents, 1, "Bonjour, %1(%s)!")
	EVENT_ENTRY(ClassWithResEvents, 2, "How old are You?")
	EVENT_ENTRY(ClassWithResEvents, 3, "I am %1(%d) years old.")
	EVENT_ENTRY(GenBasicEventTransResEvents, 1, "%1(%s) failed.\n")
	EVENT_ENTRY(GenBasicEventTransResEvents, 2, "%1(%s)\n\n")
	EVENT_ENTRY(GenBasicEventTransResEvents, 3, "Syntax: '%1(%s)' <-s EventDefSourceFile>, <-t TranslationFile>, <-o EventsDLLResFile>\n\n")
	EVENT_ENTRY(GenBasicEventTransResEvents, 4, "%1(%s)\n\n")
	EVENT_ENTRY(GenBasicEventTransResEvents, 5, "Can not open '%1(%s)'\n\n")
	EVENT_ENTRY(GenBasicEventTransResEvents, 6, "Not all translations have been found\n\n")
	EVENT_ENTRY(SomethingEvents, 1, "doing something interresting..., priority = %1(%d), value = %2(%d), You're not dreaming, the priority is %1(%d).")
	EVENT_ENTRY(SomethingEvents, 2, "Here is a double: %1(%0.3f).")
	EVENT_ENTRY(SomethingEvents, 3, "Here is a sized string: %1(%10s).")
	EVENT_ENTRY(TestEventsDLLEvents, 1, "%1(%s) failed.\n")
	EVENT_ENTRY(TestEventsDLLEvents, 2, "%1(%s)\n\n")
	EVENT_ENTRY(TestEventsDLLEvents, 3, "Syntax: '%1(%s)' <-s EventDefSourceFile>\n\n")
	EVENT_ENTRY(TestEventsDLLEvents, 4, "%1(%s)\n\n")
	EVENT_ENTRY(TestEventsDLLEvents, 5, "Can not open '%1(%s)'\n\n")
	EVENT_ENTRY(test_event_multilang_events, 1, "The %1(%d) years old %2(%s) is not %3(%s).\n")
	EVENT_ENTRY(test_event_multilang_events, 2, "Le %2(%s) age de %1(%d) ans n'est pas %3(%s).\n")
END_EVENT_ENTRY()
