
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl IBASICEVENTCORBA
// ------------------------------
#ifndef IBASICEVENTCORBA_EXPORT_H
#define IBASICEVENTCORBA_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (IBASICEVENTCORBA_HAS_DLL)
#  define IBASICEVENTCORBA_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && IBASICEVENTCORBA_HAS_DLL */

#if !defined (IBASICEVENTCORBA_HAS_DLL)
#  define IBASICEVENTCORBA_HAS_DLL 1
#endif /* ! IBASICEVENTCORBA_HAS_DLL */

#if defined (IBASICEVENTCORBA_HAS_DLL) && (IBASICEVENTCORBA_HAS_DLL == 1)
#  if defined (IBASICEVENTCORBA_BUILD_DLL)
#    define IBASICEVENTCORBA_Export ACE_Proper_Export_Flag
#    define IBASICEVENTCORBA_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define IBASICEVENTCORBA_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* IBASICEVENTCORBA_BUILD_DLL */
#    define IBASICEVENTCORBA_Export ACE_Proper_Import_Flag
#    define IBASICEVENTCORBA_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define IBASICEVENTCORBA_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* IBASICEVENTCORBA_BUILD_DLL */
#else /* IBASICEVENTCORBA_HAS_DLL == 1 */
#  define IBASICEVENTCORBA_Export
#  define IBASICEVENTCORBA_SINGLETON_DECLARATION(T)
#  define IBASICEVENTCORBA_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* IBASICEVENTCORBA_HAS_DLL == 1 */

// Set IBASICEVENTCORBA_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (IBASICEVENTCORBA_NTRACE)
#  if (ACE_NTRACE == 1)
#    define IBASICEVENTCORBA_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define IBASICEVENTCORBA_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !IBASICEVENTCORBA_NTRACE */

#if (IBASICEVENTCORBA_NTRACE == 1)
#  define IBASICEVENTCORBA_TRACE(X)
#else /* (IBASICEVENTCORBA_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define IBASICEVENTCORBA_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (IBASICEVENTCORBA_NTRACE == 1) */

#endif /* IBASICEVENTCORBA_EXPORT_H */

// End of auto generated file.
